#!/bin/sh
#
# Inital Setup see:
#    https://asciidoctor.org/docs/asciidoctor-revealjs/

SRCFILE=index.adoc
CMD="asciidoctor-revealjs -a revealjsdir=https://cdn.jsdelivr.net/npm/reveal.js@4.3.1 $SRCFILE"

echo "Rendering $SRCFILE with $CMD"
$CMD

#echo "Starting Webserver on :8000"
#jbang httpd@jbangdev >/dev/null 2>&1 & 

#open http://localhost:8000 > /dev/null &

echo "Watching *.adoc for changes"
fswatch -e ".*" -i "\\.adoc$" . |
while read events; do
  echo $events
  $CMD
done
